[package]
name = "jigsaw-doubler"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Blue Cheetah"]
repository = "https://github.com/bluecheetah001/jigsaw-doubler"

[dependencies]
humantime = "2.1.0"
itertools = "0.13.0"
varisat = "0.2.2"
